#include "seam/phase12c/live_voice.hpp"
#include "human_fixture.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <limits>
namespace seam::phase12c {
namespace { constexpr double kPi=3.14159265358979323846;
float at(const LiveVoicebankResource&r,double p,const UnitSpan&u){
 if(r.mono.empty())return 0; const auto lb=std::min<std::uint32_t>(u.loopBegin,u.end-1), le=std::max(lb+1,std::min(u.loopEnd,u.end));
 if(p>=le)p=lb+std::fmod(p-lb,double(le-lb)); if(p<0)p=0; auto i=std::min<std::size_t>(std::size_t(p),r.mono.size()-1);auto j=std::min(i+1,r.mono.size()-1);float t=float(p-i);return r.mono[i]+(r.mono[j]-r.mono[i])*t;
}}
std::size_t LiveVoicebankResource::bytes()const noexcept{return mono.size()*sizeof(float)+units.size()*sizeof(UnitSpan)+contentHash.size();}
bool LiveVoicebankResource::valid()const noexcept{if(!trusted||sampleRate<8000||sampleRate>192000||mono.empty()||bytes()>kMaxResourceBytes)return false;for(auto&u:units)if(u.begin>=u.end||u.end>mono.size()||u.loopBegin<u.begin||u.loopEnd>u.end||u.loopBegin>=u.loopEnd)return false;return true;}
std::shared_ptr<const LiveVoicebankResource> makeEmbeddedHumanResource(){auto r=std::make_shared<LiveVoicebankResource>();r->sampleRate=fixture::kSampleRate;r->trusted=true;r->contentHash=fixture::kDerivedPcmSha256;r->mono.reserve(fixture::kPcm.size());for(auto v:fixture::kPcm)r->mono.push_back(float(v)/32768.f);const auto n=std::uint32_t(r->mono.size());const auto a=std::max(2u,n*15u/100u),s=std::max(a+2,n*28u/100u),e=std::max(s+2,n*82u/100u);r->units={{UnitKind::Attack,0,s,a,s,60,-1,-1},{UnitKind::Sustain,s,e,s,e,60,-1,-1},{UnitKind::Transition,a,e,s,e,60,60,62},{UnitKind::Release,e,n,e,n,60,-1,-1}};return r;}
bool ResourcePublisher::publish(std::shared_ptr<const LiveVoicebankResource>r)noexcept{if(!r||!r->valid())return false;int p=published_.load(std::memory_order_acquire),a=audio_.load(std::memory_order_acquire),slot=0;for(int i=0;i<3;++i)if(i!=p&&i!=a){slot=i;break;}slots_[slot]=std::move(r);published_.store(slot,std::memory_order_release);generation_.fetch_add(1,std::memory_order_release);return true;}
const LiveVoicebankResource*ResourcePublisher::acquireForAudio()noexcept{int p=published_.load(std::memory_order_acquire);if(p<0)return nullptr;audio_.store(p,std::memory_order_release);return slots_[p].get();}
void ResourcePublisher::releaseFromAudio()noexcept{audio_.store(-1,std::memory_order_release);}std::uint64_t ResourcePublisher::generation()const noexcept{return generation_.load(std::memory_order_acquire);}
LiveVoiceEngine::LiveVoiceEngine(){publishResource(makeEmbeddedHumanResource());configure(48000,2);}
void LiveVoiceEngine::configure(std::uint32_t sr,std::uint32_t ch)noexcept{sampleRate_=std::clamp(sr,8000u,192000u);outputChannels_=std::clamp(ch,1u,8u);}
bool LiveVoiceEngine::publishResource(std::shared_ptr<const LiveVoicebankResource>r)noexcept{return publisher_.publish(std::move(r));}
void LiveVoiceEngine::reset()noexcept{for(auto&v:voices_)v={};channelBend_.fill(0);stats_={};resource_=nullptr;}
LiveStats LiveVoiceEngine::stats()const noexcept{return stats_;}
const UnitSpan*LiveVoiceEngine::choose(UnitKind kind,int key,int from)const noexcept{if(!resource_)return nullptr;const UnitSpan*best=nullptr;int score=9999;for(auto&u:resource_->units){if(u.kind!=kind)continue;if(kind==UnitKind::Transition&&from>=0&&u.fromKey>=0&&u.fromKey!=from)continue;int d=std::abs(int(u.rootKey)-key);if(d<score){score=d;best=&u;}}return best;}
LiveVoiceEngine::Voice*LiveVoiceEngine::allocateVoice()noexcept{for(auto&v:voices_)if(!v.active)return &v;auto*best=&voices_[0];for(auto&v:voices_)if(v.envelope<best->envelope||(v.envelope==best->envelope&&v.age<best->age))best=&v;best->tailSample=best->lastSample;best->tailLength=best->tailRemaining=std::max(64u,std::uint32_t(std::ceil(sampleRate_*.0015)));++stats_.steals;return best;}
void LiveVoiceEngine::applyEvent(const LiveEvent&e,const LiveVoicebankResource*r)noexcept{resource_=r;if(!r)return;int ch=std::clamp<int>(e.channel,0,15);if(e.type==EventType::Midi1){++stats_.midiEvents;auto st=e.midi[0]&0xF0,mc=e.midi[0]&0x0F;if(st==0x90&&e.midi[2]){LiveEvent x=e;x.type=EventType::NoteOn;x.channel=mc;x.key=e.midi[1];x.value=e.midi[2]/127.f;applyEvent(x,r);}else if(st==0x80||(st==0x90&&e.midi[2]==0)){LiveEvent x=e;x.type=EventType::NoteOff;x.channel=mc;x.key=e.midi[1];applyEvent(x,r);}else if(st==0xE0){int v=int(e.midi[1])|(int(e.midi[2])<<7);channelBend_[mc]=float(v-8192)/8192.f*2.f;}else if(st==0xD0){for(auto&v:voices_)if(v.active&&v.channel==mc)v.pressure=e.midi[1]/127.f;}else if(st==0xB0&&e.midi[1]==74){for(auto&v:voices_)if(v.active&&v.channel==mc)v.timbre=e.midi[2]/127.f;}return;}
 if(e.type==EventType::PitchBend){channelBend_[ch]=std::clamp(e.value,-48.f,48.f);++stats_.expressionEvents;return;}if(e.type==EventType::Pressure||e.type==EventType::Timbre||e.type==EventType::Brightness){for(auto&v:voices_)if(v.active&&(e.noteId<0||v.noteId==e.noteId)){if(e.type==EventType::Pressure)v.pressure=std::clamp(e.value,0.f,1.f);if(e.type==EventType::Timbre)v.timbre=std::clamp(e.value,0.f,1.f);if(e.type==EventType::Brightness)v.brightness=std::clamp(e.value,0.f,1.f);}++stats_.expressionEvents;return;}
 if(e.type==EventType::NoteOn&&e.value>0){int from=-1;for(auto&v:voices_)if(v.active&&!v.releasing&&v.channel==ch){from=v.key;break;}auto*v=allocateVoice();float tail=v->tailSample;auto tr=v->tailRemaining,tl=v->tailLength;*v={};v->tailSample=tail;v->tailRemaining=tr;v->tailLength=tl;v->active=true;v->noteId=e.noteId;v->channel=ch;v->key=e.key;v->velocity=std::clamp(e.value,0.f,1.f);v->age=++ageCounter_;v->sustain=choose(UnitKind::Sustain,e.key);v->release=choose(UnitKind::Release,e.key);auto*attack=choose(UnitKind::Attack,e.key);auto*transition=from>=0?choose(UnitKind::Transition,e.key,from):nullptr;if(transition){v->sustain=transition;v->position=transition->begin;++stats_.transitionHits;}else{v->position=attack?attack->begin:(v->sustain?v->sustain->begin:0);if(from>=0)++stats_.transitionFallbacks;}v->increment=std::pow(2.0,(double(e.key)-double(v->sustain?v->sustain->rootKey:60)+channelBend_[ch])/12.0)*double(r->sampleRate)/sampleRate_;++stats_.noteOns;return;}
 if(e.type==EventType::NoteOff||e.type==EventType::NoteChoke||(e.type==EventType::NoteOn&&e.value<=0)){for(auto&v:voices_)if(v.active&&(e.noteId>=0?v.noteId==e.noteId:(v.channel==ch&&v.key==e.key))){if(e.type==EventType::NoteChoke){v.tailSample=v.lastSample;v.tailLength=v.tailRemaining=std::max(64u,std::uint32_t(std::ceil(sampleRate_*.0015)));v.envelope=0;v.releasing=true;}else v.releasing=true;}++stats_.noteOffs;}
}
float LiveVoiceEngine::renderVoice(Voice&v,const LiveVoicebankResource&r)noexcept{if(!v.active||!v.sustain)return 0;v.increment=std::pow(2.0,(double(v.key)-double(v.sustain->rootKey)+channelBend_[std::clamp<int>(v.channel,0,15)])/12.0)*double(r.sampleRate)/sampleRate_;if(v.releasing)v.envelope=std::max(0.f,v.envelope-1.f/std::max(64.f,float(sampleRate_)*.025f));else v.envelope=std::min(1.f,v.envelope+1.f/std::max(64.f,float(sampleRate_)*.008f));if(v.releasing&&v.envelope<=0){v.active=false;return 0;}float x=at(r,v.position,*v.sustain);v.position+=v.increment;float color=.75f+.25f*v.pressure;float y=x*v.envelope*v.velocity*color;if(v.tailRemaining){float t=float(v.tailRemaining)/std::max(1u,v.tailLength);y+=v.tailSample*std::sin(t*float(kPi)*.5f);--v.tailRemaining;}v.lastSample=y;return y;}
void LiveVoiceEngine::renderRange(float*const*out,std::uint32_t ch,std::uint32_t b,std::uint32_t e,const LiveVoicebankResource*r)noexcept{for(std::uint32_t i=b;i<e;++i){float x=0;if(r)for(auto&v:voices_)x+=renderVoice(v,*r);x=std::clamp(x,-1.f,1.f);for(std::uint32_t c=0;c<ch;++c)out[c][i]=x;++stats_.renderedFrames;}}
void LiveVoiceEngine::process(std::span<const LiveEvent>events,float*const*out,std::uint32_t ch,std::uint32_t frames)noexcept{ch=std::clamp(ch,1u,8u);for(std::uint32_t c=0;c<ch;++c)if(out[c])std::fill(out[c],out[c]+frames,0.f);resource_=publisher_.acquireForAudio();if(!resource_||!resource_->valid()){publisher_.releaseFromAudio();return;}std::uint32_t cur=0;for(auto&e:events){auto off=std::min(e.sampleOffset,frames);renderRange(out,ch,cur,off,resource_);applyEvent(e,resource_);cur=off;}renderRange(out,ch,cur,frames,resource_);publisher_.releaseFromAudio();}
void LiveVoiceEngine::noteOn(std::int32_t id,std::int32_t key,float vel)noexcept{resource_=publisher_.acquireForAudio();applyEvent({0,EventType::NoteOn,id,0,std::int16_t(key),vel,{}},resource_);publisher_.releaseFromAudio();}
void LiveVoiceEngine::noteOff(std::int32_t id,std::int32_t key)noexcept{resource_=publisher_.acquireForAudio();applyEvent({0,EventType::NoteOff,id,0,std::int16_t(key),0,{}},resource_);publisher_.releaseFromAudio();}
float LiveVoiceEngine::renderSample()noexcept{resource_=publisher_.acquireForAudio();float x=0;if(resource_&&resource_->valid())for(auto&v:voices_)x+=renderVoice(v,*resource_);publisher_.releaseFromAudio();return std::clamp(x,-1.f,1.f);}
} // namespace seam::phase12c
