from __future__ import annotations

from .evidence import JsonObject, JsonValue
from .seam_to_ustx_maps import export_meters, export_tempos
from .seam_to_ustx_part import export_part
from .ustx_study_contracts import (
    BridgeError,
    ConversionContext,
    MAXIMUM_NOTES,
    MAXIMUM_PARTS,
    MAXIMUM_TRACKS,
    array_value,
    integer_value,
    object_value,
    optional_boolean,
    optional_number,
    optional_string,
    required,
)


def convert_seam_to_ustx(root: JsonObject, context: ConversionContext) -> JsonObject:
    if root.get("formatId") != "com.project-seam.project":
        raise BridgeError("unsupported SEAM project format")
    schema = integer_value(required(root, "schemaVersion", "project"), "schemaVersion")
    if schema != 7:
        raise BridgeError("study bridge exports only SEAM schema 7")
    ppq = integer_value(required(root, "ppq", "project"), "project.ppq")
    if ppq <= 0 or ppq > 32767:
        raise BridgeError("project.ppq is invalid")
    tempos, tempo_points = export_tempos(root, ppq, context)
    meters, meter_points = export_meters(root, ppq, context)
    vocal_values = array_value(
        required(root, "vocalTracks", "project"), "project.vocalTracks"
    )
    if len(vocal_values) > MAXIMUM_TRACKS:
        raise BridgeError("SEAM track count exceeds the study limit")
    tracks: list[JsonValue] = []
    parts: list[JsonValue] = []
    note_count = 0
    for index, value in enumerate(vocal_values):
        path = f"project.vocalTracks[{index}]"
        track = object_value(value, path)
        voicebank = object_value(
            required(track, "voicebank", path), f"{path}.voicebank"
        )
        character = object_value(
            required(track, "character", path), f"{path}.character"
        )
        context.loss(
            "SEAM_BANK_REFERENCE_NOT_EXPORTED",
            f"{path}.voicebank",
            f"SEAM bank {voicebank.get('id', '')!r} was not emitted as an executable singer reference",
        )
        context.loss(
            "SEAM_CHARACTER_REFERENCE_NOT_EXPORTED",
            f"{path}.character",
            f"SEAM character {character.get('id', '')!r} has no USTX identity field",
        )
        context.loss(
            "SEAM_OUTPUT_ROUTE_NOT_EXPORTED",
            f"{path}.outputRoute",
            "SEAM bus routing is outside the USTX study subset",
        )
        tracks.append(
            {
                "track_name": optional_string(
                    track, "name", f"Track {index + 1}", path
                ),
                "track_color": "Blue",
                "mute": optional_boolean(track, "muted", False, path),
                "solo": optional_boolean(track, "solo", False, path),
                "volume": optional_number(track, "gainDb", 0.0, path),
                "pan": optional_number(track, "pan", 0.0, path),
                "track_expressions": [],
                "voice_color_names": [""],
            }
        )
        regions = array_value(required(track, "regions", path), f"{path}.regions")
        if len(parts) + len(regions) > MAXIMUM_PARTS:
            raise BridgeError("SEAM region count exceeds the study limit")
        for region_index, region in enumerate(regions):
            part = export_part(
                region,
                index,
                region_index,
                ppq,
                tempo_points,
                meter_points,
                context,
            )
            notes = part["notes"]
            assert isinstance(notes, list)
            note_count += len(notes)
            parts.append(part)
    if note_count > MAXIMUM_NOTES:
        raise BridgeError("SEAM note count exceeds the study limit")
    audio_tracks = array_value(
        required(root, "audioTracks", "project"), "project.audioTracks"
    )
    if audio_tracks:
        context.loss(
            "SEAM_AUDIO_TRACKS_NOT_EXPORTED",
            "project.audioTracks",
            "USTX study export contains vocal tracks only",
        )
    tempo_values: list[JsonValue] = list(tempos)
    meter_values: list[JsonValue] = list(meters)
    return {
        "ustx_version": "0.9",
        "name": optional_string(root, "name", "SEAM Study Export", "project"),
        "comment": "Generated by the Project SEAM study-only bridge",
        "output_dir": "Vocal",
        "cache_dir": "UCache",
        "expressions": {},
        "exp_selectors": [
            "dyn",
            "pitd",
            "clr",
            "eng",
            "vel",
            "vol",
            "atk",
            "dec",
            "gen",
            "bre",
        ],
        "exp_primary": 0,
        "exp_secondary": 1,
        "key": 0,
        "time_signatures": meter_values,
        "tempos": tempo_values,
        "tracks": tracks,
        "voice_parts": parts,
    }
