from __future__ import annotations

import json
from typing import Final

try:
    from .release_gate_validation import JsonObject, JsonValue
except ImportError:
    from release_gate_validation import JsonObject, JsonValue


PROTOCOLS: Final[JsonObject] = {
    "assisted-comparison": {"id":"fp.protocol.assisted-comparison.v1","constraints":{"design":"WITHIN_CREATOR_COUNTERBALANCED","taskOrders":["MANUAL_THEN_ASSISTED","ASSISTED_THEN_MANUAL"],"material":"MATCHED_UNFAMILIAR","startingConditions":"EQUAL","permittedTools":"EQUAL","priorExposure":"RECORDED","taskEvidence":"ACTUAL_SAVED_SONG_TASKS","comparisonMetric":"MEDIAN_WITHIN_CREATOR_CORRECTION_SECONDS","comparison":"ASSISTED_STRICTLY_LESS_THAN_MANUAL","maxRemainingPronunciationDefects":0,"maxRemainingTimingDefects":0}},
    "producer-acceptance": {"id":"fp.protocol.producer-acceptance.v1","constraints":{"sourceRoutes":["REAL_RECORD_OR_IMPORT","PROCEDURAL_GENERATION"],"operations":["EDIT","RETAKE_OR_REGENERATE","INDEPENDENT_REVIEW","PACKAGE","INSTALL","CREATE_UNSEEN_SONG","SAVE","REOPEN","EXPORT"],"requiredSurfaces":["NATIVE_UI","SHARED_BATCH_ACTIONS"],"songExtent":"COMPLETE_SONG","handoff":"EXACT_INSTALLED_RESOURCE","manualJsonPatching":"FORBIDDEN"}},
    "accessibility-acceptance": {"id":"fp.protocol.accessibility-acceptance.v1","constraints":{"operations":["SELECT_OVERLAPS","READ_COMPLETE_TEXT","EDIT_REQUIRED_CONTROLS"],"layoutConditions":["NARROW","STANDARD","SCALED"],"inputModes":["POINTER","KEYBOARD","ACCESSIBILITY_SEMANTICS"],"motionModes":["FULL","REDUCED"],"missingArtwork":"EDITOR_REMAINS_OPERABLE"}},
    "interchange-acceptance": {"id":"fp.protocol.interchange-acceptance.v1","constraints":{"formats":["USTX","SMF"],"surfaces":["NATIVE_IMPORT","NATIVE_EXPORT"],"preservedFields":["TEMPO","METER","PPQ","MUSICAL_INTENT"],"conversionLoss":"EXPLICIT","externalCode":"NEVER_EXECUTE","inputLimits":"BEFORE_ALLOCATION"}},
    "host-acceptance": {"id":"fp.protocol.host-acceptance.v1","constraints":{"surfaces":"BOTH_STANDALONES_AND_ALL_NINE_HOST_TUPLES","liveChecks":["PER_NOTE_TARGETING","PAN","VIBRATO","TIMBRE","PEDAL","PANIC"],"timingModes":["FIXED_AUDIO","FOLLOW_HOST"],"scenarios":["NONZERO_START","TEMPO_CHANGE","SEEK","LOOP","STOP_RESTART","STATE_RELOAD","MULTIPLE_INSTANCES","OFFLINE_BOUNCE"],"finalRequiredVocalStates":["CURRENT_READY"],"forbiddenSuccessfulBounceStates":["PENDING","FAILED","STALE","MISSING"],"insufficientHostHistory":"EXPLICIT_DIAGNOSTIC"}},
    "release-acceptance": {"id":"fp.protocol.release-acceptance.v1","constraints":{"evidenceClass":"EXACT_SIGNED_INSTALLED","platforms":["macos-arm64","windows-x86_64"],"requirements":["INSTALL_UPDATE_UNINSTALL","ALL_NINE_HOST_TUPLES","U60","RECOVERY","CONSENTED_SUPPORT_EXPORT_DELETE","PRIVACY"],"sessionMinutes":[30,120],"maxUnresolvedBlockerCritical":0,"maxDataLossEvents":0}},
    "gate-acceptance": {"id":"fp.protocol.gate-acceptance.v1","constraints":{"auditInput":"RESTORED_CANDIDATE_BOUND_RAW_EVIDENCE","requiredTransitions":["PROMOTE","RESUME","CLOSE","PUBLIC_PREDECESSOR"],"authority":"AUTHENTICATED_CURRENT_AUDIT","assertionOnlyFlags":"REJECT","readyImpliesClosed":False}},
    "rights-acceptance": {"id":"fp.protocol.rights-acceptance.v1","constraints":{"sourceKinds":["HUMAN","PROCEDURAL","NEURAL"],"assetKinds":["SAMPLE","RECIPE_DEPENDENCY","DATASET","MODEL","VOCODER","DICTIONARY","CHARACTER"],"permissionTypes":["SOURCE_USE","TRANSFORMATION","REDISTRIBUTION","COMMERCIAL_RENDER","TRAINING_MODEL"],"applicability":"EXACT_ASSET_REVIEW","humanSourceRelabeling":"REJECT","changedAssetReview":"INVALIDATE"}},
    "independent-review": {"id":"fp.protocol.independent-review.v1","constraints":{"attribution":"PSEUDONYMOUS_INDEPENDENT_IDENTITIES","producerReviewerRelation":"DISTINCT_PEOPLE","generatorSelfApproval":"REJECT","languageQualification":"NATIVE_REVIEW_FOR_JA_EN_KO","rawEvidence":"HASH_BOUND","rejectedMaterial":"RESOLVE_AND_RETEST","approvalScope":"EXACT_RESOURCE_WORKLOAD_REVISION"}},
}

CHECKS: Final[JsonObject] = {
    "fp.check.R1.cross-note-melody.v1": {"id":"fp.check.R1.cross-note-melody.v1","caseId":"R1.cross-note-melody","requiredOperations":["RENDER_SOURCE_UNIT_OVER_C4_G4","MEASURE_COMPLETE_NOTE_TRAJECTORY"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R1.syllable-order.v1": {"id":"fp.check.R1.syllable-order.v1","caseId":"R1.syllable-order","requiredOperations":["RENDER_TWO_SYLLABLES_IN_ONE_NOTE","MEASURE_ORDERED_CONSONANT_VOWEL_SPANS"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R1.melisma-articulation.v1": {"id":"fp.check.R1.melisma-articulation.v1","caseId":"R1.melisma-articulation","requiredOperations":["LINK_ONE_SYLLABLE_ACROSS_PITCHES","COUNT_RETRIGGERS","DIAGNOSE_SHORT_NOTE_CONSTRAINTS"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R1.timing-tempo.v1": {"id":"fp.check.R1.timing-tempo.v1","caseId":"R1.timing-tempo","requiredOperations":["APPLY_30MS_PHONE_BOUNDARY_EDIT","CHANGE_TEMPO","MEASURE_SAMPLE_DISPLACEMENT"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.vibrato.v1": {"id":"fp.check.R2.vibrato.v1","caseId":"R2.vibrato","requiredOperations":["EDIT_VIBRATO_ONSET_RATE_DEPTH_FADES_PHASE","MEASURE_SINGLE_OSCILLATION"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.pitch-portamento.v1": {"id":"fp.check.R2.pitch-portamento.v1","caseId":"R2.pitch-portamento","requiredOperations":["EDIT_LOCAL_PITCH_AND_PORTAMENTO_SHAPE_DURATION","MEASURE_TARGET_TRAJECTORY"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.dynamics-gain.v1": {"id":"fp.check.R2.dynamics-gain.v1","caseId":"R2.dynamics-gain","requiredOperations":["EDIT_TYPED_GAIN_CURVE","MEASURE_CLICK_FREE_LOUDNESS"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.consonant-attack.v1": {"id":"fp.check.R2.consonant-attack.v1","caseId":"R2.consonant-attack","requiredOperations":["EDIT_CONSONANT_PLACEMENT_ATTACK","MEASURE_PHONEME_PLAN"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.legato-melisma.v1": {"id":"fp.check.R2.legato-melisma.v1","caseId":"R2.legato-melisma","requiredOperations":["LINK_SYLLABLE_NOTE_OWNERSHIP","VERIFY_RETRIGGER_POLICY"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.style-blend.v1": {"id":"fp.check.R2.style-blend.v1","caseId":"R2.style-blend","requiredOperations":["SELECT_REVIEWED_STYLE","BLEND_PAIRED_UNITS"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.breath-release.v1": {"id":"fp.check.R2.breath-release.v1","caseId":"R2.breath-release","requiredOperations":["EDIT_BREATH_EVENT_LEVEL_RELEASE","MEASURE_UNVOICED_BOUNDARIES"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.breathiness.v1": {"id":"fp.check.R2.breathiness.v1","caseId":"R2.breathiness","requiredOperations":["EDIT_NOISE_VOICING_BALANCE","REVIEW_INTELLIGIBILITY"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.tension-power.v1": {"id":"fp.check.R2.tension-power.v1","caseId":"R2.tension-power","requiredOperations":["EDIT_VOCAL_EFFORT","MEASURE_SPECTRUM_INDEPENDENT_OF_GAIN"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.formant-timbre.v1": {"id":"fp.check.R2.formant-timbre.v1","caseId":"R2.formant-timbre","requiredOperations":["EDIT_FORMANT_ENVELOPE","MEASURE_F0_INDEPENDENCE"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.growl-roughness.v1": {"id":"fp.check.R2.growl-roughness.v1","caseId":"R2.growl-roughness","requiredOperations":["EDIT_APERIODIC_SUBHARMONIC_COMPONENT","REVIEW_CONTROLLED_ROUGHNESS"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.automatic-performance.v1": {"id":"fp.check.R2.automatic-performance.v1","caseId":"R2.automatic-performance","requiredOperations":["PROPOSE_AND_ACCEPT_EDITABLE_PITCH_TIMING_ENERGY_ARTICULATION"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.takes-harmonies.v1": {"id":"fp.check.R2.takes-harmonies.v1","caseId":"R2.takes-harmonies","requiredOperations":["SAVE_SEED_TAKE","CREATE_INDEPENDENT_EDITABLE_HARMONY"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R2.persistence-neutral.v1": {"id":"fp.check.R2.persistence-neutral.v1","caseId":"R2.persistence-neutral","requiredOperations":["TEST_NEUTRAL_DEFAULTS","UNDO","RECOVER","RELOAD","REUSE_CACHE","EXPORT_ALL_EXPRESSIONS"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R3.original-female-recipe.v1": {"id":"fp.check.R3.original-female-recipe.v1","caseId":"R3.original-female-recipe","requiredOperations":["DESIGN_FEMALE_VOICE_WITHOUT_HUMAN_RECORDING","SAVE_EDITABLE_RECIPE"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R3.phonetic-range.v1": {"id":"fp.check.R3.phonetic-range.v1","caseId":"R3.phonetic-range","requiredOperations":["GENERATE_VOWELS_CONSONANTS_TRANSITIONS","SING_UNSEEN_LYRICS_ACROSS_DECLARED_RANGE"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R3.voice-song-separation.v1": {"id":"fp.check.R3.voice-song-separation.v1","caseId":"R3.voice-song-separation","requiredOperations":["EDIT_RECIPE","PRESERVE_INSTALLED_BANK_AND_OLD_SONG","EDIT_SONG_PITCH_WITHOUT_RECIPE_MUTATION"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R4.real-input.v1": {"id":"fp.check.R4.real-input.v1","caseId":"R4.real-input","requiredOperations":["RECORD_OR_IMPORT_REAL_SOURCE","COMPLETE_PRODUCER_PROTOCOL"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.producer-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R4.generated-input.v1": {"id":"fp.check.R4.generated-input.v1","caseId":"R4.generated-input","requiredOperations":["GENERATE_PROCEDURAL_SOURCE","COMPLETE_PRODUCER_PROTOCOL"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.producer-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R5.qa-lineage.v1": {"id":"fp.check.R5.qa-lineage.v1","caseId":"R5.qa-lineage","requiredOperations":["QA_VOICED_BREATH_PAUSE_CLOSURE","BIND_EXPLICIT_TAKE_OWNER","INVALIDATE_REVIEW_ON_REVISION"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.producer-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R5.versioned-install.v1": {"id":"fp.check.R5.versioned-install.v1","caseId":"R5.versioned-install","requiredOperations":["PUBLISH_IMMUTABLE_GENERATION_ATOMICALLY","VERIFY_PACKAGE_HASHES","INSTALL","REPRODUCE_BANK"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.producer-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R5.interruption-recovery.v1": {"id":"fp.check.R5.interruption-recovery.v1","caseId":"R5.interruption-recovery","requiredOperations":["INTERRUPT_CANCEL_OR_EXHAUST_DISK","REJECT_STALE_WRITER","RESTORE_PRIOR_APPROVED_VERSION"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.producer-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R6.inventory-range.v1": {"id":"fp.check.R6.inventory-range.v1","caseId":"R6.inventory-range","requiredOperations":["RESOLVE_FULL_DECLARED_INVENTORY","REVIEW_RANGE_ON_HELD_OUT_PHRASES"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R6.two-styles.v1": {"id":"fp.check.R6.two-styles.v1","caseId":"R6.two-styles","requiredOperations":["REVIEW_TWO_DISTINCT_STYLES","REJECT_HIDDEN_SUBSTITUTION"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R6.paired-blend.v1": {"id":"fp.check.R6.paired-blend.v1","caseId":"R6.paired-blend","requiredOperations":["BLEND_SUPPORTED_PAIRED_STYLES","MEASURE_PITCH_AND_IDENTITY_PRESERVATION"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R7.ja-pronunciation.v1": {"id":"fp.check.R7.ja-pronunciation.v1","caseId":"R7.ja-pronunciation","requiredOperations":["USE_JA_RULES_DICTIONARY","EDIT_PRONUNCIATION","RENDER_APPROVED_JA_RESOURCE","COMPLETE_NATIVE_REVIEWED_SONG"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R7.en-pronunciation.v1": {"id":"fp.check.R7.en-pronunciation.v1","caseId":"R7.en-pronunciation","requiredOperations":["USE_EN_RULES_DICTIONARY","EDIT_PRONUNCIATION","RENDER_APPROVED_EN_RESOURCE","COMPLETE_NATIVE_REVIEWED_SONG"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R7.ko-pronunciation.v1": {"id":"fp.check.R7.ko-pronunciation.v1","caseId":"R7.ko-pronunciation","requiredOperations":["USE_KO_RULES_DICTIONARY","EDIT_PRONUNCIATION","RENDER_APPROVED_KO_RESOURCE","COMPLETE_NATIVE_REVIEWED_SONG"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R7.edit-reconciliation.v1": {"id":"fp.check.R7.edit-reconciliation.v1","caseId":"R7.edit-reconciliation","requiredOperations":["INSERT_PHONE_OR_CHANGE_DICTIONARY","PRESERVE_IDENTITY_BOUND_LOCKS","RETAIN_AMBIGUITY","UNDO"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R8.classical-range.v1": {"id":"fp.check.R8.classical-range.v1","caseId":"R8.classical-range","requiredOperations":["MEASURE_PITCH_FORMANTS_DURATION_JOINS_VOICED_COVERAGE_OVER_DECLARED_RANGE"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R8.independent-transitions.v1": {"id":"fp.check.R8.independent-transitions.v1","caseId":"R8.independent-transitions","requiredOperations":["RETARGET_VOICED_TRANSITION","PRESERVE_UNVOICED_DETAIL","VERIFY_INDEPENDENT_SOURCE_MAPPING"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R8.selection-capabilities.v1": {"id":"fp.check.R8.selection-capabilities.v1","caseId":"R8.selection-capabilities","requiredOperations":["BOUND_CONTEXTUAL_SELECTION","TEST_RAW_REQUIRED_CONTROLS","VERIFY_FALLBACK_CACHE_PROVENANCE"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R9.dataset-model.v1": {"id":"fp.check.R9.dataset-model.v1","caseId":"R9.dataset-model","requiredOperations":["QUALIFY_ORIGINAL_DATASET","REJECT_SPLIT_LEAKAGE","VERIFY_ACOUSTIC_VOCODER_COMPATIBILITY"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R9.installed-inference.v1": {"id":"fp.check.R9.installed-inference.v1","caseId":"R9.installed-inference","requiredOperations":["INSTALL_QUALIFIED_MODEL_ON_BOTH_TARGETS","RENDER_UNFAMILIAR_SONG","CANCEL","RECOVER","EXPORT"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R9.provider-closure.v1": {"id":"fp.check.R9.provider-closure.v1","caseId":"R9.provider-closure","requiredOperations":["BIND_CPU_PROVIDER_PRECISION_HELPER_PROTOCOL_RUNTIME_TO_INSTALLED_SURFACE"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R10.manual-ownership.v1": {"id":"fp.check.R10.manual-ownership.v1","caseId":"R10.manual-ownership","requiredOperations":["REGENERATE_PARTIAL_RANGE","PRESERVE_LOCKED_CHANNELS","REJECT_STALE_ACCEPTANCE","PREVENT_DOUBLE_VIBRATO"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.assisted-comparison.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R10.take-harmony-editing.v1": {"id":"fp.check.R10.take-harmony-editing.v1","caseId":"R10.take-harmony-editing","requiredOperations":["COMPARE_REPEATABLE_TAKES","EDIT_INDEPENDENT_HARMONY","UNDO","RELOAD","EXPORT"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.assisted-comparison.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R10.assisted-benefit.v1": {"id":"fp.check.R10.assisted-benefit.v1","caseId":"R10.assisted-benefit","requiredOperations":["RUN_COUNTERBALANCED_UNFAMILIAR_TASKS","COMPARE_WITHIN_CREATOR_CORRECTION_WORK","COUNT_REMAINING_ERRORS"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.assisted-comparison.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R11.musical-editing.v1": {"id":"fp.check.R11.musical-editing.v1","caseId":"R11.musical-editing","requiredOperations":["DUPLICATE_UNEQUAL_NOTES","EDIT_TEMPO_METER","DISTRIBUTE_LYRICS","EDIT_ALL_EXPRESSION_LANES"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.accessibility-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R11.dense-accessibility.v1": {"id":"fp.check.R11.dense-accessibility.v1","caseId":"R11.dense-accessibility","requiredOperations":["SELECT_DENSE_OVERLAPS","READ_FULL_LONG_TEXT","EDIT_NARROW_SCALED_LAYOUT","USE_KEYBOARD_ACCESSIBILITY"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.accessibility-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R12.ustx-roundtrip.v1": {"id":"fp.check.R12.ustx-roundtrip.v1","caseId":"R12.ustx-roundtrip","requiredOperations":["NATIVE_USTX_IMPORT_EXPORT","MEASURE_TEMPO_PPQ_FIDELITY","REPORT_CONVERSION_LOSS"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.interchange-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R12.smf-roundtrip.v1": {"id":"fp.check.R12.smf-roundtrip.v1","caseId":"R12.smf-roundtrip","requiredOperations":["NATIVE_SMF_IMPORT_EXPORT","MEASURE_TEMPO_METER_PPQ_FIDELITY","REPORT_CONVERSION_LOSS"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.interchange-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R12.hostile-input.v1": {"id":"fp.check.R12.hostile-input.v1","caseId":"R12.hostile-input","requiredOperations":["REJECT_MALFORMED_OVERSIZED_EXECUTABLE_REFERENCES_BEFORE_ALLOCATION"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.interchange-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R13.standalone-authoring.v1": {"id":"fp.check.R13.standalone-authoring.v1","caseId":"R13.standalone-authoring","requiredOperations":["AUTHOR_IN_BOTH_STANDALONES","RUN_PER_NOTE_LIVE_EXPRESSION"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.host-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R13.macos-arm64-reaper-clap.v1": {"id":"fp.check.R13.macos-arm64-reaper-clap.v1","caseId":"R13.macos-arm64-reaper-clap","requiredOperations":["RUN_EXACT_INSTALLED_HOST_TUPLE","RUN_HOST_TIMING_AND_CURRENT_AUDIO_BOUNCE_PROTOCOL"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.host-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R13.macos-arm64-reaper-vst3.v1": {"id":"fp.check.R13.macos-arm64-reaper-vst3.v1","caseId":"R13.macos-arm64-reaper-vst3","requiredOperations":["RUN_EXACT_INSTALLED_HOST_TUPLE","RUN_HOST_TIMING_AND_CURRENT_AUDIO_BOUNCE_PROTOCOL"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.host-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R13.windows-x86_64-reaper-clap.v1": {"id":"fp.check.R13.windows-x86_64-reaper-clap.v1","caseId":"R13.windows-x86_64-reaper-clap","requiredOperations":["RUN_EXACT_INSTALLED_HOST_TUPLE","RUN_HOST_TIMING_AND_CURRENT_AUDIO_BOUNCE_PROTOCOL"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.host-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R13.windows-x86_64-reaper-vst3.v1": {"id":"fp.check.R13.windows-x86_64-reaper-vst3.v1","caseId":"R13.windows-x86_64-reaper-vst3","requiredOperations":["RUN_EXACT_INSTALLED_HOST_TUPLE","RUN_HOST_TIMING_AND_CURRENT_AUDIO_BOUNCE_PROTOCOL"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.host-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R13.macos-arm64-bitwig-clap.v1": {"id":"fp.check.R13.macos-arm64-bitwig-clap.v1","caseId":"R13.macos-arm64-bitwig-clap","requiredOperations":["RUN_EXACT_INSTALLED_HOST_TUPLE","RUN_HOST_TIMING_AND_CURRENT_AUDIO_BOUNCE_PROTOCOL"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.host-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R13.macos-arm64-bitwig-vst3.v1": {"id":"fp.check.R13.macos-arm64-bitwig-vst3.v1","caseId":"R13.macos-arm64-bitwig-vst3","requiredOperations":["RUN_EXACT_INSTALLED_HOST_TUPLE","RUN_HOST_TIMING_AND_CURRENT_AUDIO_BOUNCE_PROTOCOL"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.host-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R13.windows-x86_64-bitwig-clap.v1": {"id":"fp.check.R13.windows-x86_64-bitwig-clap.v1","caseId":"R13.windows-x86_64-bitwig-clap","requiredOperations":["RUN_EXACT_INSTALLED_HOST_TUPLE","RUN_HOST_TIMING_AND_CURRENT_AUDIO_BOUNCE_PROTOCOL"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.host-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R13.windows-x86_64-bitwig-vst3.v1": {"id":"fp.check.R13.windows-x86_64-bitwig-vst3.v1","caseId":"R13.windows-x86_64-bitwig-vst3","requiredOperations":["RUN_EXACT_INSTALLED_HOST_TUPLE","RUN_HOST_TIMING_AND_CURRENT_AUDIO_BOUNCE_PROTOCOL"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.host-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R13.macos-arm64-logic-pro-auv2.v1": {"id":"fp.check.R13.macos-arm64-logic-pro-auv2.v1","caseId":"R13.macos-arm64-logic-pro-auv2","requiredOperations":["RUN_EXACT_INSTALLED_HOST_TUPLE","RUN_HOST_TIMING_AND_CURRENT_AUDIO_BOUNCE_PROTOCOL"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.host-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R14.singer-identity.v1": {"id":"fp.check.R14.singer-identity.v1","caseId":"R14.singer-identity","requiredOperations":["DISPLAY_ACTIVE_SINGER_STYLE_RANGE_STATUS","AUDITION","VERIFY_AUTHORIZED_ARTWORK_BINDING"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.accessibility-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R14.synchronized-performance.v1": {"id":"fp.check.R14.synchronized-performance.v1","caseId":"R14.synchronized-performance","requiredOperations":["SYNCHRONIZE_MOUTH_WITH_RENDERED_PERFORMANCE","SEEK_LOOP_STOP_RELOAD","KEEP_CALLBACK_INDEPENDENT"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.accessibility-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R14.reduced-motion.v1": {"id":"fp.check.R14.reduced-motion.v1","caseId":"R14.reduced-motion","requiredOperations":["TEST_NARROW_LAYOUT_LONG_LABELS_MISSING_ART","USE_REDUCED_MOTION_AND_ACCESSIBILITY"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.accessibility-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R15.bounded-work.v1": {"id":"fp.check.R15.bounded-work.v1","caseId":"R15.bounded-work","requiredOperations":["ENFORCE_INPUT_OUTPUT_MEMORY_MODEL_GENERATION_LIMITS","CANCEL_WITH_DEADLINE_OUTSIDE_CALLBACK"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R15.immutable-publication.v1": {"id":"fp.check.R15.immutable-publication.v1","caseId":"R15.immutable-publication","requiredOperations":["REJECT_STALE_CONTEXT_ASSET_REQUESTS","COMPARE_WRITER_GENERATIONS","PRESERVE_MANUAL_ACCEPTED_WORK"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R15.save-recovery.v1": {"id":"fp.check.R15.save-recovery.v1","caseId":"R15.save-recovery","requiredOperations":["RECOVER_JOURNAL_SAVE_AND_INTERRUPTED_GENERATION","REJECT_DATA_LOSS_AND_HIDDEN_SUCCESS"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R15.classical-small-edit.v1": {"id":"fp.check.R15.classical-small-edit.v1","caseId":"R15.classical-small-edit","requiredOperations":["MEASURE_FROZEN_CLASSICAL_SMALL_EDIT_WARM_COLD_P95"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R15.legacy-preview.v1": {"id":"fp.check.R15.legacy-preview.v1","caseId":"R15.legacy-preview","requiredOperations":["MEASURE_LEGACY_48KHZ_2S_PREVIEW_MEDIAN_AND_P95"],"requiredProtocolIds":["fp.protocol.independent-review.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R16.ja-corpus.v1": {"id":"fp.check.R16.ja-corpus.v1","caseId":"R16.ja-corpus","requiredOperations":["RUN_60_JA_PHRASES_OVER_RELEASED_RANGE_STYLE_CAPABILITIES"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.assisted-comparison.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R16.en-corpus.v1": {"id":"fp.check.R16.en-corpus.v1","caseId":"R16.en-corpus","requiredOperations":["RUN_60_EN_PHRASES_OVER_RELEASED_RANGE_STYLE_CAPABILITIES"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.assisted-comparison.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R16.ko-corpus.v1": {"id":"fp.check.R16.ko-corpus.v1","caseId":"R16.ko-corpus","requiredOperations":["RUN_60_KO_PHRASES_OVER_RELEASED_RANGE_STYLE_CAPABILITIES"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.assisted-comparison.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R16.finished-songs.v1": {"id":"fp.check.R16.finished-songs.v1","caseId":"R16.finished-songs","requiredOperations":["COMPLETE_THREE_JA_EN_KO_SONGS_WITH_PROCEDURAL_AND_NEURAL_RESOURCES"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.assisted-comparison.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R16.independent-creators.v1": {"id":"fp.check.R16.independent-creators.v1","caseId":"R16.independent-creators","requiredOperations":["RUN_FIVE_INDEPENDENT_CREATORS_ON_BOTH_PLATFORMS","COMPLETE_SAVED_SONG_AND_REAL_GENERATED_PRODUCER_JOURNEYS"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.assisted-comparison.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R16.acoustic-listening.v1": {"id":"fp.check.R16.acoustic-listening.v1","caseId":"R16.acoustic-listening","requiredOperations":["RETAIN_DRY_AUDIO_OBJECTIVE_SCORES_VOICED_COVERAGE_OCTAVE_ERRORS","REVIEW_INTELLIGIBILITY_IDENTITY_ARTIFACTS_USEFULNESS","RETEST_REJECTIONS"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.assisted-comparison.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R17.signed-install.v1": {"id":"fp.check.R17.signed-install.v1","caseId":"R17.signed-install","requiredOperations":["VERIFY_EXACT_SIGNED_INSTALLED_BYTES_ON_BOTH_TARGETS","INSTALL_UPDATE_UNINSTALL"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.release-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R17.soak-hosts.v1": {"id":"fp.check.R17.soak-hosts.v1","caseId":"R17.soak-hosts","requiredOperations":["RUN_ALL_NINE_HOSTS_AND_STANDALONES","RUN_30_AND_120_MINUTE_SOAKS","RECOVER_MULTIPLE_INSTANCES"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.release-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R17.u60-support.v1": {"id":"fp.check.R17.u60-support.v1","caseId":"R17.u60-support","requiredOperations":["COMPLETE_U60_FORCED_CRASH_RECOVERY","REVIEW_SUPPORT_PRIVACY_CONSENT_EXPORT_DELETE","BIND_CANDIDATE"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.release-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R18.coverage-admission.v1": {"id":"fp.check.R18.coverage-admission.v1","caseId":"R18.coverage-admission","requiredOperations":["REJECT_LEGACY_FORGED_MISSING_DUPLICATE_UNKNOWN_DEFERRED_GLOBALLY_UNSUPPORTED_PROOF"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.gate-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R18.content-lineage.v1": {"id":"fp.check.R18.content-lineage.v1","caseId":"R18.content-lineage","requiredOperations":["REHASH_CONTRACT_RESOURCES_INSTALLED_BYTES_RAW_ARCHIVE","INVALIDATE_SUBSTITUTION"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.gate-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R18.promotion-closure.v1": {"id":"fp.check.R18.promotion-closure.v1","caseId":"R18.promotion-closure","requiredOperations":["REPRODUCE_READY_CLOSED_AUDITS_FOR_TRANSITIONS_AND_PUBLIC_PREDECESSOR","REJECT_FLAGS_AND_SHALLOW_SUMMARIES"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.gate-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R19.sources-transforms.v1": {"id":"fp.check.R19.sources-transforms.v1","caseId":"R19.sources-transforms","requiredOperations":["REVIEW_CONTRIBUTING_HUMAN_GENERATED_SOURCES_AND_RECIPE_DEPENDENCIES","VERIFY_APPLICABLE_PERMISSIONS"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.rights-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R19.training-model.v1": {"id":"fp.check.R19.training-model.v1","caseId":"R19.training-model","requiredOperations":["REVIEW_DATASET_SPLIT_MODEL_VOCODER_PROVENANCE_AND_TRAINING_DISTRIBUTION_RIGHTS"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.rights-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R19.dictionary-character.v1": {"id":"fp.check.R19.dictionary-character.v1","caseId":"R19.dictionary-character","requiredOperations":["REVIEW_EXACT_DICTIONARY_CHARACTER_RIGHTS","REJECT_STALE_SUBSTITUTED_ASSETS"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.rights-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R20.shared-actions.v1": {"id":"fp.check.R20.shared-actions.v1","caseId":"R20.shared-actions","requiredOperations":["USE_SHARED_VALIDATED_UI_CLI_BATCH_ACTIONS","REJECT_MANUAL_JSON_PATCHING"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.producer-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R20.batch-lineage.v1": {"id":"fp.check.R20.batch-lineage.v1","caseId":"R20.batch-lineage","requiredOperations":["RESUME_BOUNDED_BATCH","BIND_IMMUTABLE_SOURCE_RECIPE_TAKE","PRESERVE_EDIT_OWNER_REVIEW_ATOMIC_PUBLICATION"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.producer-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.R20.installed-song.v1": {"id":"fp.check.R20.installed-song.v1","caseId":"R20.installed-song","requiredOperations":["INSTALL_REVIEWED_BANK_MODEL","CREATE_UNFAMILIAR_SONG","SAVE","REOPEN","EXPORT"],"requiredProtocolIds":["fp.protocol.independent-review.v1","fp.protocol.producer-acceptance.v1"],"evidenceMode":"RAW_ARTIFACTS_AND_TYPED_OBSERVATIONS"},
    "fp.check.chunk-continuity.v1": {"id":"fp.check.chunk-continuity.v1","comparison":"WHOLE_PHRASE_VS_FORCED_CHUNKS","partitionLocations":["INSIDE_VOICED_SUSTAIN","INSIDE_PHONETIC_CONTEXT"],"minimumChunks":2,"requiredObservations":["PHONEME_COUNT","PHONEME_START_END_SAMPLES","F0_TRAJECTORY_CENTS","MODULATION_PHASE_RADIANS","PCM_BOUNDARY_ERROR"],"toleranceCriterion":"reproducibility-tolerances","phonemeCountComparison":"EQUAL","timingAuthority":"ONE_COMPILED_PHRASE_PLAN","phaseAuthority":"ABSOLUTE_PHRASE_TIME","neighborMutation":"EDIT_ADJACENT_PHONETIC_CONTEXT","requiredInvalidation":["PRONUNCIATION_PLAN","PERFORMANCE_PLAN","AFFECTED_CHUNK_DEPENDENCY_HASH","AFFECTED_CACHED_AUDIO"],"unaffectedChunkPolicy":"PRESERVE_WHEN_DEPENDENCIES_MATCH"},
}

CONTINUITY_CASES: Final = frozenset(["R1.cross-note-melody","R1.melisma-articulation","R2.vibrato","R2.legato-melisma","R7.ja-pronunciation","R7.en-pronunciation","R7.ko-pronunciation","R7.edit-reconciliation"])


def canonical_definition_errors(value: JsonValue, expected: JsonValue, label: str) -> list[str]:
    try:
        actual = json.dumps(value, sort_keys=True, separators=(",", ":"), allow_nan=False)
        canonical = json.dumps(expected, sort_keys=True, separators=(",", ":"), allow_nan=False)
    except (ValueError, TypeError):
        return [f"{label}: invalid canonical protocol definition"]
    return [] if actual == canonical else [f"{label}: canonical protocol constraints differ"]


def required_check_ids(identifier: str) -> tuple[str, ...]:
    checks = (f"fp.check.{identifier}.v1",)
    return (*checks, "fp.check.chunk-continuity.v1") if identifier in CONTINUITY_CASES else checks


def catalog_definition_errors(value: JsonValue, expected: JsonObject, label: str) -> list[str]:
    if not isinstance(value, dict):
        return [f"{label}: canonical protocol catalog required"]
    errors: list[str] = []
    if set(value) != set(expected):
        errors.append(f"{label}: missing or unknown canonical protocol IDs")
    for identifier, definition in expected.items():
        errors.extend(canonical_definition_errors(value.get(identifier), definition, f"{label} {identifier}"))
    return errors
