#pragma once

#include "seam/domain/project.hpp"
#include <span>
#include <optional>
#include <vector>

namespace seam::synthesis {
enum class PhonemeTimingPolicy { SourceDependent, ProceduralInNote };
inline constexpr std::uint32_t kProceduralTimingPolicyRevision = 3U;
struct PhonemeTimingAnchor final {
  domain::PhonemeKey key;
  time::SampleFrame nucleusFrame{0};
  time::SampleFrame endFrame{0};
  // Absent means the token start needs role/source-dependent interpretation;
  // it must not be presented as a resolved onset at the nucleus frame.
  std::optional<time::SampleFrame> explicitStartFrame;
  std::uint16_t syllableIndex{0U};
  // Absent for nucleus-free material: nucleusFrame is then a fallback time
  // anchor, not evidence of a voiced vowel or an invented phoneme identity.
  std::optional<domain::PhonemeKey> nucleusKey;
  bool endExplicit{false};
  std::optional<bool> voiced{};
  // Generated by an explicit compiler policy, never an authored timing edit.
  std::optional<time::SampleFrame> inferredStartFrame{};
};

// Default syllable allocation is equal elapsed time between tempo-resolved note
// endpoints. Explicit token offsets remain relative to the note's start.
// Nuclei must stay strictly ordered. Automatic ends follow the next nucleus;
// an explicit end crossing it is a conflict, not a silently clamped edit.
// ProceduralInNote reserves min(60 ms, one quarter syllable) for a single
// onset in a wholly untimed syllable, with a one-frame minimum. Voiced onsets
// retain their voicing identity; timing does not grant a renderer capability.
// One coda may reserve the same bounded duration from the syllable end, with
// the vowel ending at its inferred start. Clusters remain source-dependent.
// Generated starts remain separate from explicit edits. Edited/unsupported
// groups retain source-dependent timing; the backend must validate them.
[[nodiscard]] core::Result<std::vector<PhonemeTimingAnchor>> compilePhonemeTimingPlan(
    const domain::Project& project, const domain::VocalRegion& region,
    std::span<const domain::PhonemeToken> tokens, std::uint32_t sampleRate,
    PhonemeTimingPolicy policy = PhonemeTimingPolicy::SourceDependent);
}
