# Call after all project targets are declared.
function(seam_check_neural_dependency_direction)
  set(pending seam_neural_synthesis)
  set(visited)
  while(pending)
    list(POP_FRONT pending current)
    get_target_property(aliased "${current}" ALIASED_TARGET)
    if(aliased)
      set(current "${aliased}")
    endif()
    if(current IN_LIST visited)
      continue()
    endif()
    list(APPEND visited "${current}")
    if(current STREQUAL "seam_authoring_runtime" OR current STREQUAL "seam_rendering")
      message(FATAL_ERROR "Neural dependency points upward to ${current}")
    endif()
    foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
      get_target_property(dependencies "${current}" "${property}")
      foreach(dependency IN LISTS dependencies)
        if(dependency MATCHES "^\\$<LINK_ONLY:([^>]+)>$")
          set(dependency "${CMAKE_MATCH_1}")
        endif()
        if(TARGET "${dependency}")
          list(APPEND pending "${dependency}")
        endif()
      endforeach()
    endforeach()
  endwhile()
endfunction()
